# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://justudin.com"
baseurl: ""

# Brief name and description of the site
title: Muhammad Syafrudin
description: "About Me: Muhammad Syafrudin | Technology Enthusiast - me_at_justudin_dot_com - @justudinlab"

# --- Outputting options --- #
# More information can be found on Jekyll's site
timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
paginate: 10
paginate_path: "/page/:num"

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/udin.jpeg"

# List of links in the navigation bar
navbar-links:
  Blog: ""
  About: "about"
  Contact:  "contact" 
#nav-search: "search"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Muhammad Syafrudin
  email: "udin@justudin.com"
#  facebook: justudin
  github: justudin
  twitter: justudinlab
  linkedin: "in/justudin"
  stackoverflow: "users/2512855/justudin" 
  
# Select which links to show in the footer  
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: true
  github: true
  linkedin: false
  stackoverflow: true
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "justudin.com" 

# --- Misc --- #

# Fill in your Disqus shortname if you want to support Disqus comments
disqus: "justudin"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-71969471-1"

fb_app_id: ""

# Default YAML values (more information on Jekyll's site)  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts 		
      show-share: true # add sharing buttons to all blog posts		
      show-subscribe: true # add subscribe email to all blog posts
      addthis-plugin: true
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

